# Generated by Django 6.0.6 on 2026-06-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='trip',
            name='travel_type',
            field=models.CharField(choices=[('solo', 'Solo'), ('family', 'Family'), ('friends', 'Friends'), ('couple', 'Couple')], max_length=20),
        ),
    ]
