# Generated by Django 6.0.6 on 2026-06-22 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_alter_trip_budget_alter_trip_travel_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TripPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_allocation', models.JSONField()),
                ('transport', models.JSONField()),
                ('hotels', models.JSONField()),
                ('restaurants', models.JSONField()),
                ('attractions', models.JSONField()),
                ('itinerary', models.JSONField()),
                ('estimated_cost', models.FloatField()),
                ('remaining_budget', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='planner.trip')),
            ],
        ),
    ]
