# Generated by Django 6.0.6 on 2026-06-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_trip_user_tripplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
